# Generated by Django 5.0.6 on 2024-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medname', models.CharField(max_length=255)),
                ('simple_generic_name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=50)),
                ('outpatients', models.IntegerField()),
                ('inpatients', models.IntegerField()),
                ('patients', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueSet',
            fields=[
                ('value_set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value_set_name', models.CharField(max_length=255)),
                ('medications', models.ManyToManyField(to='valuesets.medication')),
            ],
        ),
    ]
